services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: katchup-backend
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - TMDB_API_TOKEN=${TMDB_API_TOKEN}
    networks:
      - app-network
    restart: unless-stopped

  ollama:
    build:
      context: .
      dockerfile: ollama/Dockerfile
    image: katchup-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports: 
      - "127.0.0.1:11434:11434"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

