version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - RUST_LOG=info
      - TMDB_API_TOKEN=${TMDB_API_TOKEN}
    networks:
      - app-network
    restart: unless-stopped

  ollama:
    build:
      context: .
      dockerfile: ollama/Dockerfile
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

