services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: katchup-backend
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=full
      - TMDB_API_TOKEN=${TMDB_API_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

